packages:
  - "backend"
  - "frontend"
allowBuilds:
  '@google/genai': true
  '@prisma/engines': true
  better-sqlite3: true
  esbuild: true
  prisma: true
  protobufjs: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - tsx@4.23.10
